## 1. Importação das bibliotecas

Este bloco importa as bibliotecas utilizadas ao longo do notebook:
- `pandas` (`pd`): leitura, organização, transformação e análise dos dados em tabelas.
- `numpy` (`np`): operações numéricas e tratamento de valores, incluindo a identificação de códigos que serão convertidos em valores ausentes.

In [1]:
import pandas as pd
import numpy as np

## 2. Leitura dos arquivos

Este bloco carrega a base do Vigitel e a tabela auxiliar de unidades federativas/capitais:
- `pd.read_csv()` lê os arquivos CSV.
- `decimal=','` informa que a vírgula é usada como separador decimal na base do Vigitel.
- `encoding='ISO-8859-1'` define a codificação usada para ler caracteres do arquivo.
- `df_vigitel.info()` exibe a quantidade de registros, as colunas, os tipos de dados e a presença de valores não nulos.
- `df_uf` recebe a tabela auxiliar `UF.csv`, lida com codificação UTF-8.

In [2]:
df_vigitel = pd.read_csv('dados/vigitel-2006-2024-peso-rake_slabel.csv',decimal=',',encoding='ISO-8859-1')

df_vigitel.info()


df_uf = pd.read_csv('dados/UF.csv',encoding='utf-8')

C:\Users\Fabio\AppData\Local\Temp\ipykernel_13996\1550531879.py:1: DtypeWarning: Columns (7,11,119,120,130,131,132,185,189,190,212,225,255,262,265,266,267,268,269,283,292,296,297,298,313,314,363,371,381,385,397,399,401,404,409,466) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vigitel = pd.read_csv('dados/vigitel-2006-2024-peso-rake_slabel.csv',decimal=',',encoding='ISO-8859-1')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 833217 entries, 0 to 833216
Columns: 486 entries, ano to insonia
dtypes: float64(405), int64(38), object(43)
memory usage: 3.0+ GB

## 3. Visualização da tabela auxiliar de UFs

A expressão `df_uf` exibe a tabela auxiliar carregada anteriormente. Isso permite conferir suas colunas e os valores disponíveis, que serão usados depois para relacionar os códigos das cidades às respectivas capitais.

In [3]:
df_uf

,codDici,Capital,Sigla UF,Código Oficial IBGE (7 dígitos)
0,1,Aracaju,SE,2800308
1,2,Belém,PA,1501402
2,3,Belo Horizonte,MG,3106200
3,4,Boa Vista,RR,1400100
4,5,Campo Grande,MS,5002704
5,6,Cuiabá,MT,5103403
6,7,Curitiba,PR,4106902
7,8,Florianópolis,SC,4205407
8,9,Fortaleza,CE,2304400
9,10,Goiânia,GO,5208707
10,11,João Pessoa,PB,2507507
11,12,Macapá,AP,1600303
12,13,Maceió,AL,2704302
13,14,Manaus,AM,1302603
14,15,Natal,RN,2408102
15,16,Palmas,TO,1721000
16,17,Porto Alegre,RS,4314902
17,18,Porto Velho,RO,1100205
18,19,Recife,PE,2611606
19,20,Rio Branco,AC,1200401
20,21,Rio de Janeiro,RJ,3304557
21,22,Salvador,BA,2927408
22,23,São Luís,MA,2111300
23,24,São Paulo,SP,3550308
24,25,Teresina,PI,2211001
25,26,Vitória,ES,3205309
26,27,Distrito Federal (Brasília),DF,5300108

## 4. Filtragem dos registros

Este bloco mantém em `df_vigitel` somente os registros que atendem simultaneamente a duas condições:
- `ano >= 2022`: registros a partir de 2022.
- `fet <= 3`: registros cujo valor da variável `fet` é menor ou igual a 3.

`fet` : representa a faixa etária : menor ou igual a 3 representa as faixa etaria entre 18 a 24 anos, 25 a 34 anos, 35 a 44 anos, que são as faixas etárias que queremos investigar  

O operador `&` combina as condições, de modo que ambas precisam ser verdadeiras para o registro ser mantido.

In [4]:
df_vigitel = df_vigitel.loc[(df_vigitel['ano'] >= 2022) & (df_vigitel['fet'] <= 3)]

## 5. Verificação das dimensões da base filtrada

`df_vigitel.shape` retorna uma tupla com a quantidade de linhas e colunas do DataFrame após a filtragem. Assim, é possível verificar o tamanho da base resultante.

In [5]:
df_vigitel.shape

(22989, 486)

## 6. Seleção das colunas de interesse

A lista `colunas_especificas` define quais variáveis serão mantidas para a análise. Em seguida, `df_vigitel[colunas_especificas]` cria `df_vigitel_2` contendo apenas essas colunas.

O comando `df_vigitel_2.info()` apresenta a estrutura dessa seleção, incluindo tipos de dados e quantidade de valores não nulos por coluna.

In [6]:
#Colunas
colunas_especificas = ['ano','cidade','pesorake2025','q6','q7','fet','q8a','q9','q11','imc_i','frutareg','refritl5','score_upp_2cat','score_upp_2cat2024','inativo_2023','ativo_livre','tv_d_3','tempo_tela_total','fumante','r403','r403a','fumantetotal','alcabu','depressao','hart','diab','obesid_i','excpeso_i','r701_hh','saruim']

df_vigitel_2 = df_vigitel[colunas_especificas]
df_vigitel_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22989 entries, 784480 to 825688
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ano                 22989 non-null  int64
 1   cidade              22989 non-null  int64
 2   pesorake2025        22989 non-null  object
 3   q6                  22989 non-null  int64
 4   q7                  22989 non-null  int64
 5   fet                 22989 non-null  int64
 6   q8a                 22989 non-null  float64
 7   q9                  22989 non-null  object
 8   q11                 22989 non-null  float64
 9   imc_i               22989 non-null  object
 10  frutareg            22989 non-null  int64
 11  refritl5            22989 non-null  float64
 12  score_upp_2cat      9110 non-null   float64
 13  score_upp_2cat2024  13879 non-null  float64
 14  inativo_2023        22989 non-null  float64
 15  ativo_livre         22989 non-null  float64
 16  tv_d_3              22989 non-null  int64
 17  tempo_tela_total    22989 non-null  float64
 18  fumante             22989 non-null  int64
 19  r403                9110 non-null   float64
 20  r403a               13879 non-null  float64
 21  fumantetotal        22989 non-null  float64
 22  alcabu              22989 non-null  int64
 23  depressao           22989 non-null  float64
 24  hart                22989 non-null  int64
 25  diab                22989 non-null  int64
 26  obesid_i            22989 non-null  int64
 27  excpeso_i           22989 non-null  int64
 28  r701_hh             13849 non-null  float64
 29  saruim              22989 non-null  int64
dtypes: float64(13), int64(14), object(3)
memory usage: 5.4+ MB

## 7. Estatísticas descritivas iniciais

`df_vigitel_2.describe()` calcula estatísticas descritivas das colunas numéricas, como quantidade de valores válidos, média, desvio-padrão, mínimo, quartis e máximo. Essas medidas ajudam a observar a distribuição inicial das variáveis.

In [7]:
df_vigitel_2.describe()

,ano,cidade,q6,q7,fet,q8a,q11,frutareg,refritl5,score_upp_2cat,...,r403a,fumantetotal,alcabu,depressao,hart,diab,obesid_i,excpeso_i,r701_hh,saruim
count,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,9110.000000,...,13879.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,13849.000000,22989.000000
mean,2023.603724,13.975336,32.661273,1.561790,2.277307,6.895211,184.518683,0.502762,0.170647,0.224149,...,3.848332,0.112445,0.252730,0.125234,0.128192,0.039323,0.244552,0.603637,6.703878,0.054722
std,0.489134,7.745885,7.495673,0.496178,0.747456,36.334310,102.176399,0.500003,0.376208,0.417044,...,0.474887,0.315920,0.434587,0.330991,0.334310,0.194367,0.429830,0.489152,1.492679,0.227441
min,2023.000000,1.000000,18.000000,1.000000,1.000000,1.000000,120.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2023.000000,7.000000,27.000000,1.000000,2.000000,5.000000,160.000000,0.000000,0.000000,0.000000,...,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000
50%,2024.000000,14.000000,33.000000,2.000000,2.000000,5.000000,168.000000,1.000000,0.000000,0.000000,...,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.000000,0.000000
75%,2024.000000,21.000000,39.000000,2.000000,3.000000,6.000000,175.000000,1.000000,0.000000,0.000000,...,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,8.000000,0.000000
max,2024.000000,27.000000,44.000000,2.000000,3.000000,888.000000,888.000000,1.000000,1.000000,1.000000,...,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,15.000000,1.000000

## 8. Combinação de variáveis e exclusão das colunas originais

Este bloco combina pares de colunas que representam versões alternativas de uma mesma informação:
- `combine_first()` preenche os valores ausentes da primeira coluna com valores disponíveis na segunda.
- O resultado é armazenado em `score_upp_2catGeral` e `r403_Geral`.
- `isna().sum()` contabiliza os valores ausentes por coluna antes da exclusão.
- `drop(columns=...)` remove as quatro colunas originais que foram combinadas, mantendo as versões consolidadas.

O uso de `.copy()` cria uma cópia explícita do DataFrame antes das alterações.

In [8]:
#Mesclando coluna score_upp_2cat com score_upp_2cat2024
df_vigitel_2 = df_vigitel_2.copy() 
df_vigitel_2['score_upp_2catGeral'] = df_vigitel_2['score_upp_2cat'].combine_first(df_vigitel_2['score_upp_2cat2024'])

df_vigitel_2['r403_Geral'] = df_vigitel_2['r403'].combine_first(df_vigitel_2['r403a'])


#Excluir variaveis mescladas
df_vigitel_2.isna().sum()
colunas_para_excluir = ['r403','r403a','score_upp_2cat','score_upp_2cat2024']
df_vigitel_2 = df_vigitel_2.drop(columns = colunas_para_excluir)

## 9. Conversão de tipos de dados

Este bloco converte as colunas `pesorake2025`, `q9` e `imc_i` para o tipo numérico `float`. Isso permite realizar cálculos matemáticos e análises estatísticas com essas variáveis, desde que seus valores possam ser convertidos para números.

In [9]:
#CONVERTER Variaveis Object para float
df_vigitel_2 = df_vigitel_2.copy()
colunas = ['pesorake2025','q9','imc_i']
df_vigitel_2[colunas] = df_vigitel_2[colunas].astype(float)

## 10. Conferência dos tipos após a conversão

`df_vigitel_2.info()` mostra novamente a estrutura do DataFrame. A saída permite conferir se as colunas selecionadas passaram a ter os tipos esperados e verificar quantos valores não nulos existem em cada uma.

In [10]:
df_vigitel_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22989 entries, 784480 to 825688
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano                  22989 non-null  int64
 1   cidade               22989 non-null  int64
 2   pesorake2025         22989 non-null  float64
 3   q6                   22989 non-null  int64
 4   q7                   22989 non-null  int64
 5   fet                  22989 non-null  int64
 6   q8a                  22989 non-null  float64
 7   q9                   22989 non-null  float64
 8   q11                  22989 non-null  float64
 9   imc_i                22989 non-null  float64
 10  frutareg             22989 non-null  int64
 11  refritl5             22989 non-null  float64
 12  inativo_2023         22989 non-null  float64
 13  ativo_livre          22989 non-null  float64
 14  tv_d_3               22989 non-null  int64
 15  tempo_tela_total     22989 non-null  float64
 16  fumante              22989 non-null  int64
 17  fumantetotal         22989 non-null  float64
 18  alcabu               22989 non-null  int64
 19  depressao            22989 non-null  float64
 20  hart                 22989 non-null  int64
 21  diab                 22989 non-null  int64
 22  obesid_i             22989 non-null  int64
 23  excpeso_i            22989 non-null  int64
 24  r701_hh              13849 non-null  float64
 25  saruim               22989 non-null  int64
 26  score_upp_2catGeral  22989 non-null  float64
 27  r403_Geral           22989 non-null  float64
dtypes: float64(14), int64(14)
memory usage: 5.1 MB

## 11. Preenchimento de valores ausentes pela média

Este bloco calcula a média das colunas `q8a` e `r701_hh` e usa essas médias para preencher os valores ausentes (`NaN`) nas respectivas colunas.

A operação `isna()` identifica as posições ausentes, e `.loc[...]` seleciona essas posições para receber a média calculada. Esse procedimento altera os valores ausentes; a média pode não ser adequada para toda variável, dependendo do significado e da distribuição dos dados.

In [11]:
#Atribui média a valores faltantes

media_coluna = df_vigitel_2['q8a'].mean()
media_coluna_h = df_vigitel_2['r701_hh'].mean()


df_vigitel_2.loc[df_vigitel_2['q8a'].isna() ,'q8a'] = media_coluna
df_vigitel_2.loc[df_vigitel_2['r701_hh'].isna() ,'r701_hh'] = media_coluna_h

## 12. Contagem de valores ausentes por coluna

`df_vigitel_2.isna().sum()` conta quantos valores ausentes existem em cada coluna após o preenchimento realizado no bloco anterior. A saída ajuda a identificar quais variáveis ainda contêm dados faltantes.

In [12]:
#VERIFICAR DADOS FALTANTES por coluna
df_vigitel_2.isna().sum()

ano                    0
cidade                 0
pesorake2025           0
q6                     0
q7                     0
fet                    0
q8a                    0
q9                     0
q11                    0
imc_i                  0
frutareg               0
refritl5               0
inativo_2023           0
ativo_livre            0
tv_d_3                 0
tempo_tela_total       0
fumante                0
fumantetotal           0
alcabu                 0
depressao              0
hart                   0
diab                   0
obesid_i               0
excpeso_i              0
r701_hh                0
saruim                 0
score_upp_2catGeral    0
r403_Geral             0
dtype: int64

## 13. Tratamento de códigos especiais e preenchimento pela média

A lista `colunas_atribui_vazio` seleciona as colunas `q8a`, `q9` e `q11`.

Para essas colunas:
- `apply()` aplica uma operação a cada coluna.
- `np.where()` substitui os códigos `888` e `777` por `NaN`.
- Uma segunda aplicação de `apply()` usa `fillna(x.mean())` para preencher os valores ausentes com a média de cada coluna.

O código comentado não é executado. Antes de tratar códigos como `777` e `888` como ausentes, é importante confirmar no dicionário de dados que esses códigos realmente representam respostas especiais, e não valores válidos.

In [13]:
#VERIFICAR DADOS FALTANTES por Linhas
colunas_atribui_vazio = ['q8a','q9','q11']

#df_vigitel_2[colunas_atribui_vazio] = df_vigitel_2[colunas_atribui_vazio].replace#((888|777),np.nan)

# O lambda avalia cada coluna (x) e substitui onde for 888 e 777
df_vigitel_2[colunas_atribui_vazio] = df_vigitel_2[colunas_atribui_vazio].apply(lambda x: np.where((x == 888) | (x == 777), np.nan, x))

# Preenche com a médias os valores NaN
df_vigitel_2[colunas_atribui_vazio] = df_vigitel_2[colunas_atribui_vazio].apply(lambda x: x.fillna(x.mean()))

## 14. Resumo estatístico após o tratamento

`df_vigitel_2.describe()` apresenta novamente as estatísticas descritivas depois das transformações e do tratamento de valores ausentes. A comparação com a saída anterior pode ajudar a observar como as alterações afetaram os dados.

In [14]:
#Atribuir a media para os nulos 
df_vigitel_2.describe()

,ano,cidade,pesorake2025,q6,q7,fet,q8a,q9,q11,imc_i,...,alcabu,depressao,hart,diab,obesid_i,excpeso_i,r701_hh,saruim,score_upp_2catGeral,r403_Geral
count,22989.000000,22989.000000,2.298900e+04,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,...,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000,22989.000000
mean,2023.603724,13.975336,1.509513e+06,32.661273,1.561790,2.277307,5.397908,75.488208,167.197180,26.971384,...,0.252730,0.125234,0.128192,0.039323,0.244552,0.603637,6.703878,0.054722,0.278699,3.857889
std,0.489134,7.745885,2.584654e+06,7.495673,0.496178,0.747456,0.918989,16.912612,10.016626,5.557243,...,0.434587,0.330991,0.334310,0.194367,0.429830,0.489152,1.158536,0.227441,0.448369,0.460872
min,2023.000000,1.000000,4.561498e+04,18.000000,1.000000,1.000000,1.000000,30.000000,120.000000,10.380623,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2023.000000,7.000000,3.768149e+05,27.000000,1.000000,2.000000,5.000000,64.000000,160.000000,23.309053,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,4.000000
50%,2024.000000,14.000000,7.339422e+05,33.000000,2.000000,2.000000,5.000000,74.000000,167.197180,26.222685,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.703878,0.000000,0.000000,4.000000
75%,2024.000000,21.000000,1.562531e+06,39.000000,2.000000,3.000000,6.000000,85.000000,174.000000,29.761906,...,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.000000,0.000000,1.000000,4.000000
max,2024.000000,27.000000,3.685761e+07,44.000000,2.000000,3.000000,8.000000,203.000000,210.000000,78.125000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,15.000000,1.000000,1.000000,4.000000

## 15. Junção com a tabela de capitais

Este bloco usa `merge()` para acrescentar a `df_vigitel_2` o nome da capital correspondente ao código presente na coluna `cidade`:
- Da tabela `df_uf`, são selecionadas as colunas `codDici` e `Capital`.
- `left_on='cidade'` e `right_on='codDici'` definem as colunas usadas para relacionar as tabelas.
- `how='left'` mantém todas as linhas da base do Vigitel, mesmo quando não há correspondência na tabela auxiliar.
- O resultado da junção é armazenado em `df_vigitel_Uf`.

A última linha, `df_vigitel_2`, exibe o DataFrame anterior à junção; para visualizar a tabela já enriquecida com o nome da capital, seria necessário exibir `df_vigitel_Uf`.

In [15]:
#Juntando Tabela UF com a tabela Vigitel para ter o nome das cidades

df_vigitel_Uf = df_vigitel_2.merge(df_uf[['codDici','Capital']],left_on='cidade',right_on='codDici',how='left')


df_vigitel_2

,ano,cidade,pesorake2025,q6,q7,fet,q8a,q9,q11,imc_i,...,alcabu,depressao,hart,diab,obesid_i,excpeso_i,r701_hh,saruim,score_upp_2catGeral,r403_Geral
784480,2023,1,5.737984e+05,30,1,2,5.0,76.0,183.0,22.694019,...,0,0.0,0,0,0,0,6.703878,0,0.0,3.0
784481,2023,1,1.237732e+06,18,1,1,5.0,98.0,182.0,29.585798,...,0,0.0,0,0,0,1,6.703878,0,0.0,4.0
784482,2023,1,1.410216e+06,40,1,3,4.0,130.0,175.0,42.448978,...,0,0.0,1,0,1,1,6.703878,0,0.0,4.0
784484,2023,1,5.737984e+05,29,1,2,6.0,100.0,185.0,29.218407,...,0,0.0,0,0,0,1,6.703878,0,0.0,4.0
784485,2023,1,6.034737e+05,38,1,3,4.0,72.0,189.0,20.156210,...,0,0.0,0,0,0,0,6.703878,0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825684,2024,21,2.642596e+06,41,2,3,6.0,98.0,163.0,36.885090,...,1,0.0,0,0,1,1,6.000000,0,0.0,4.0
825685,2024,3,1.878169e+06,36,2,3,6.0,76.0,165.0,27.915520,...,0,0.0,0,0,0,1,5.000000,1,0.0,4.0
825686,2024,26,4.600292e+05,22,2,1,6.0,68.0,165.0,24.977043,...,0,0.0,0,1,0,0,6.000000,0,0.0,4.0
825687,2024,26,2.276502e+05,36,2,3,6.0,85.0,167.0,30.477966,...,0,0.0,1,1,1,1,5.000000,0,0.0,4.0
825688,2024,3,2.541602e+06,39,2,3,7.0,52.0,156.0,21.367521,...,0,0.0,0,0,0,0,4.000000,0,0.0,4.0

## 16. Exportação dos dados para CSV

`to_csv('dados_Vigitel_Analise.csv')` grava o DataFrame `df_vigitel_Uf` em um arquivo CSV chamado `dados_Vigitel_Analise.csv`. O arquivo contém os dados após a junção com a tabela de capitais.

Como o argumento `index` foi definido, o Pandas não inclui o índice do DataFrame como uma coluna adicional no arquivo exportado.

In [16]:
df_vigitel_Uf.to_csv('dados/dados_Vigitel_Analise.csv',index=False)